import { simpleGit } from "simple-git";

export interface BitbucketAdapterOptions {
  /** App password or API token with pullrequest:write. */
  token: string;
  /** Username for Basic auth (Bitbucket Cloud). */
  username: string;
  /** `workspace/repo_slug` */
  repo: string;
  defaultBranch?: string;
  /** For Bitbucket Server, override. Defaults to Cloud. */
  apiBaseUrl?: string;
}

const DEFAULT_API = "https://api.bitbucket.org/2.0";

export function createBitbucketAdapter(options: BitbucketAdapterOptions) {
  const baseUrl = options.apiBaseUrl ?? DEFAULT_API;
  const defaultBranch = options.defaultBranch ?? "main";
  const authHeader =
    "Basic " +
    Buffer.from(`${options.username}:${options.token}`).toString("base64");

  return {
    async createRemediationPr(input: {
      repoPath: string;
      branchName: string;
      commitMessage: string;
      prTitle: string;
      prBody: {
        issue: { id: string; title: string };
        agentName: string;
        agentEmoji: string;
        explanation: string;
        filesChanged: string[];
      };
      labels?: string[];
    }): Promise<{ number: number; url: string; nodeId: string }> {
      const git = simpleGit(input.repoPath);
      const status = await git.status();
      const base = status.current ?? defaultBranch;
      await git.checkoutBranch(input.branchName, base);
      await git.add(".");
      await git.commit(input.commitMessage, undefined, {
        "--author": "Marinara <marinara@oh-pen-testing.local>",
      });
      await git.push("origin", input.branchName, ["--set-upstream"]);

      const body = buildBody(input.prBody);
      const res = await fetch(
        `${baseUrl}/repositories/${options.repo}/pullrequests`,
        {
          method: "POST",
          headers: {
            Authorization: authHeader,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            title: input.prTitle,
            description: body,
            source: { branch: { name: input.branchName } },
            destination: { branch: { name: defaultBranch } },
            close_source_branch: true,
          }),
        },
      );
      if (!res.ok) {
        throw new Error(
          `Bitbucket PR creation failed: ${res.status} ${await res.text()}`,
        );
      }
      const data = (await res.json()) as {
        id: number;
        links: { html: { href: string } };
      };
      return {
        number: data.id,
        url: data.links.html.href,
        nodeId: String(data.id),
      };
    },
  };
}

function buildBody(p: {
  issue: { id: string; title: string };
  agentName: string;
  agentEmoji: string;
  explanation: string;
  filesChanged: string[];
}): string {
  return `## 🛡️ Oh Pen Testing fix — ${p.issue.id}

**Fixed by:** ${p.agentName} ${p.agentEmoji}

### What this fixes

${p.issue.title}

### How this fix works

${p.explanation}

### Files changed

${p.filesChanged.map((f) => `- \`${f}\``).join("\n")}

---

_Generated by [Oh Pen Testing](https://github.com/Oh-Pen-Sauce/oh-pen-testing)._`;
}
