import type { Issue, Severity } from "@oh-pen-testing/shared";

export interface PrBodyInput {
  issue: Issue;
  agentName: string;
  agentEmoji: string;
  explanation: string;
  filesChanged: string[];
}

export function buildPrBody(input: PrBodyInput): string {
  const { issue, agentName, agentEmoji, explanation, filesChanged } = input;
  const explanationSafe = sanitiseMarkdown(explanation);
  const severityBadge = severityBadgeText(issue.severity);
  const owasp = issue.owasp_category ? `**Category:** ${issue.owasp_category}` : "";
  const cwe = issue.cwe.length > 0 ? `**CWE:** ${issue.cwe.join(", ")}` : "";
  const files = filesChanged.map((f) => `- \`${f}\``).join("\n");

  return `## 🛡️ Oh Pen Testing fix — ${issue.id}

${owasp}
${cwe}
**Severity:** ${severityBadge}${issue.cvss_score ? ` (CVSS ${issue.cvss_score})` : ""}
**Fixed by:** ${agentName} ${agentEmoji}

### What was wrong

${sanitiseMarkdown(issue.evidence.analysis)}

### How this fix works

${explanationSafe}

### Files changed

${files}

### Reviewer checklist

- [ ] Fix handles edge cases (empty input, unicode, very long strings)
- [ ] No behaviour change for legitimate input
- [ ] Error handling is equivalent or better

---

_Generated by [Oh Pen Testing](https://github.com/Oh-Pen-Sauce/oh-pen-testing). Discovered by \`${issue.discovered_by}\`._`;
}

function severityBadgeText(severity: Severity): string {
  const map: Record<Severity, string> = {
    info: "Info",
    low: "Low",
    medium: "Medium",
    high: "High",
    critical: "**Critical**",
  };
  return map[severity];
}

/**
 * Strip/escape content that could break markdown or inject formatting tricks.
 * AI-generated explanations are treated as untrusted.
 */
export function sanitiseMarkdown(input: string): string {
  return (
    input
      // Remove HTML tags
      .replace(/<[^>]+>/g, "")
      // Escape triple backticks that could close our fence
      .replace(/```/g, "`\u200b``")
      // Cap length
      .slice(0, 4000)
  );
}
