import { simpleGit } from "simple-git";

export interface GitLabAdapterOptions {
  token: string;
  /** `group/subgroup/project` — GitLab path with namespace. */
  repo: string;
  defaultBranch?: string;
  /** Self-hosted GitLab URL. Defaults to gitlab.com. */
  apiBaseUrl?: string;
}

export interface GitLabMergeRequestResult {
  iid: number;
  url: string;
  id: number;
}

export interface GitLabRemediationInput {
  repoPath: string;
  branchName: string;
  commitMessage: string;
  author?: { name: string; email: string };
  title: string;
  body: string;
  labels?: string[];
}

const DEFAULT_API = "https://gitlab.com/api/v4";

export function createGitLabAdapter(options: GitLabAdapterOptions) {
  const baseUrl = options.apiBaseUrl ?? DEFAULT_API;
  const defaultBranch = options.defaultBranch ?? "main";
  const projectPath = encodeURIComponent(options.repo);

  return {
    async createRemediationMergeRequest(
      input: GitLabRemediationInput,
    ): Promise<GitLabMergeRequestResult> {
      const git = simpleGit(input.repoPath);
      const status = await git.status();
      const base = status.current ?? defaultBranch;
      await git.checkoutBranch(input.branchName, base);
      await git.add(".");
      const author = input.author ?? {
        name: "Marinara",
        email: "marinara@oh-pen-testing.local",
      };
      await git.commit(input.commitMessage, undefined, {
        "--author": `${author.name} <${author.email}>`,
      });
      await git.push("origin", input.branchName, ["--set-upstream"]);

      const res = await fetch(
        `${baseUrl}/projects/${projectPath}/merge_requests`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "PRIVATE-TOKEN": options.token,
          },
          body: JSON.stringify({
            source_branch: input.branchName,
            target_branch: defaultBranch,
            title: input.title,
            description: input.body,
            labels: (input.labels ?? []).join(","),
            remove_source_branch: true,
          }),
        },
      );
      if (!res.ok) {
        throw new Error(
          `GitLab MR creation failed: ${res.status} ${await res.text()}`,
        );
      }
      const data = (await res.json()) as {
        iid: number;
        web_url: string;
        id: number;
      };
      return { iid: data.iid, url: data.web_url, id: data.id };
    },

    /**
     * Shape-compatible with the GitHubAdapter so callers can treat them
     * interchangeably. The PR orchestrator in core calls
     * createRemediationPr — we alias here.
     */
    async createRemediationPr(input: {
      repoPath: string;
      branchName: string;
      commitMessage: string;
      prTitle: string;
      prBody: {
        issue: { id: string; title: string };
        agentName: string;
        agentEmoji: string;
        explanation: string;
        filesChanged: string[];
      };
      labels?: string[];
    }): Promise<{ number: number; url: string; nodeId: string }> {
      const body = buildBody(input.prBody);
      const result = await this.createRemediationMergeRequest({
        repoPath: input.repoPath,
        branchName: input.branchName,
        commitMessage: input.commitMessage,
        title: input.prTitle,
        body,
        labels: input.labels,
      });
      return {
        number: result.iid,
        url: result.url,
        nodeId: String(result.id),
      };
    },
  };
}

interface PrBodyPayload {
  issue: { id: string; title: string };
  agentName: string;
  agentEmoji: string;
  explanation: string;
  filesChanged: string[];
}

function buildBody(p: PrBodyPayload): string {
  return `## 🛡️ Oh Pen Testing fix — ${p.issue.id}

**Fixed by:** ${p.agentName} ${p.agentEmoji}

### What this fixes

${p.issue.title}

### How this fix works

${p.explanation}

### Files changed

${p.filesChanged.map((f) => `- \`${f}\``).join("\n")}

---

_Generated by [Oh Pen Testing](https://github.com/Oh-Pen-Sauce/oh-pen-testing)._`;
}
